rpc:
  name: "Jy-rpc"
  version: "1.0"
  serverHost: "localhost"
  serverPort: 8081
  mock: false
  serializer: "jdk"
  loadBalance: "random"
  retryStrategy: "noRetry"
  TolerantStrategy: "failFast"
  registryConfig:
    registry: "redis"
    #    registry: "zookeeper"
    #   address: "localhost:2181"
    address: "localhost:6379"
    #    username: "user"
    #    password: "pass"
    timeout: 10000

