rpc:
  name: "Jy-rpc"
  version: "1.0"
  serverHost: "localhost"
  #rpc服务器端口
  serverPort: 8081
  mock: false
  serializer: jdk
  #注册中心配置
  registryConfig:
    registry: "redis"
#    registry: "zookeeper"
#   address: "localhost:2181"
    address: "localhost:6379"
#    username: "user"
#    password: "pass"
    timeout: 10000
